<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>slitherin</AssemblyName>
    <RootNamespace>SlitherIn</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
    <PackageReference Include="System.Text.Json" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SlitherIn.Tests" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Ui\Icons\icon.ico" LogicalName="SlitherIn.Ui.Icons.icon" />
    <EmbeddedResource Include="Ui\Icons\alert.ico" LogicalName="SlitherIn.Ui.Icons.alert" />
  </ItemGroup>

</Project>